/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiThreadsRouteImport } from './routes/api/threads'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCanvasRouteImport } from './routes/api/canvas'
import { Route as ApiAutomationsRouteImport } from './routes/api/automations'
import { Route as ApiArtifactsRouteImport } from './routes/api/artifacts'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCanvasRouteImport } from './routes/_app.canvas'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppArtifactsRouteImport } from './routes/_app.artifacts'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings/index'
import { Route as AppCanvasIndexRouteImport } from './routes/_app.canvas.index'
import { Route as ApiThreadsThreadIdRouteImport } from './routes/api/threads.$threadId'
import { Route as ApiSettingsMcpTokenRouteImport } from './routes/api/settings/mcp-token'
import { Route as ApiMcpToolsRouteImport } from './routes/api/mcp/tools'
import { Route as ApiMcpServersRouteImport } from './routes/api/mcp/servers'
import { Route as ApiDashboardHistoryRouteImport } from './routes/api/dashboard.history'
import { Route as ApiCanvasCanvasIdRouteImport } from './routes/api/canvas.$canvasId'
import { Route as ApiAutomationsAutomationIdRouteImport } from './routes/api/automations.$automationId'
import { Route as ApiArtifactsArtifactIdRouteImport } from './routes/api/artifacts.$artifactId'
import { Route as AppSettingsModelRouteImport } from './routes/_app.settings/model'
import { Route as AppSettingsMcpRouteImport } from './routes/_app.settings/mcp'
import { Route as AppSettingsDataRouteImport } from './routes/_app.settings/data'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app.settings/appearance'
import { Route as AppChatThreadIdRouteImport } from './routes/_app.chat.$threadId'
import { Route as AppCanvasCanvasIdRouteImport } from './routes/_app.canvas.$canvasId'
import { Route as ApiDashboardSnapshotsSnapshotIdRouteImport } from './routes/api/dashboard.snapshots.$snapshotId'
import { Route as ApiCanvasCanvasIdNodesRouteImport } from './routes/api/canvas.$canvasId.nodes'
import { Route as ApiCanvasCanvasIdEdgesRouteImport } from './routes/api/canvas.$canvasId.edges'
import { Route as ApiAutomationsAutomationIdRunsRouteImport } from './routes/api/automations.$automationId.runs'
import { Route as ApiCanvasCanvasIdNodesNodeIdRouteImport } from './routes/api/canvas.$canvasId.nodes.$nodeId'
import { Route as ApiCanvasCanvasIdNodesNodeIdVersionsRouteImport } from './routes/api/canvas.$canvasId.nodes.$nodeId.versions'
import { Route as ApiCanvasCanvasIdNodesNodeIdGenerateRouteImport } from './routes/api/canvas.$canvasId.nodes.$nodeId.generate'
import { Route as ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRouteImport } from './routes/api/canvas.$canvasId.nodes.$nodeId.versions.$versionId.restore'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiThreadsRoute = ApiThreadsRouteImport.update({
  id: '/api/threads',
  path: '/api/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasRoute = ApiCanvasRouteImport.update({
  id: '/api/canvas',
  path: '/api/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationsRoute = ApiAutomationsRouteImport.update({
  id: '/api/automations',
  path: '/api/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsRoute = ApiArtifactsRouteImport.update({
  id: '/api/artifacts',
  path: '/api/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCanvasRoute = AppCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppArtifactsRoute = AppArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppCanvasIndexRoute = AppCanvasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCanvasRoute,
} as any)
const ApiThreadsThreadIdRoute = ApiThreadsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ApiThreadsRoute,
} as any)
const ApiSettingsMcpTokenRoute = ApiSettingsMcpTokenRouteImport.update({
  id: '/api/settings/mcp-token',
  path: '/api/settings/mcp-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpToolsRoute = ApiMcpToolsRouteImport.update({
  id: '/api/mcp/tools',
  path: '/api/mcp/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpServersRoute = ApiMcpServersRouteImport.update({
  id: '/api/mcp/servers',
  path: '/api/mcp/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardHistoryRoute = ApiDashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApiDashboardRoute,
} as any)
const ApiCanvasCanvasIdRoute = ApiCanvasCanvasIdRouteImport.update({
  id: '/$canvasId',
  path: '/$canvasId',
  getParentRoute: () => ApiCanvasRoute,
} as any)
const ApiAutomationsAutomationIdRoute =
  ApiAutomationsAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => ApiAutomationsRoute,
  } as any)
const ApiArtifactsArtifactIdRoute = ApiArtifactsArtifactIdRouteImport.update({
  id: '/$artifactId',
  path: '/$artifactId',
  getParentRoute: () => ApiArtifactsRoute,
} as any)
const AppSettingsModelRoute = AppSettingsModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMcpRoute = AppSettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDataRoute = AppSettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppChatThreadIdRoute = AppChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppCanvasCanvasIdRoute = AppCanvasCanvasIdRouteImport.update({
  id: '/$canvasId',
  path: '/$canvasId',
  getParentRoute: () => AppCanvasRoute,
} as any)
const ApiDashboardSnapshotsSnapshotIdRoute =
  ApiDashboardSnapshotsSnapshotIdRouteImport.update({
    id: '/snapshots/$snapshotId',
    path: '/snapshots/$snapshotId',
    getParentRoute: () => ApiDashboardRoute,
  } as any)
const ApiCanvasCanvasIdNodesRoute = ApiCanvasCanvasIdNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => ApiCanvasCanvasIdRoute,
} as any)
const ApiCanvasCanvasIdEdgesRoute = ApiCanvasCanvasIdEdgesRouteImport.update({
  id: '/edges',
  path: '/edges',
  getParentRoute: () => ApiCanvasCanvasIdRoute,
} as any)
const ApiAutomationsAutomationIdRunsRoute =
  ApiAutomationsAutomationIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => ApiAutomationsAutomationIdRoute,
  } as any)
const ApiCanvasCanvasIdNodesNodeIdRoute =
  ApiCanvasCanvasIdNodesNodeIdRouteImport.update({
    id: '/$nodeId',
    path: '/$nodeId',
    getParentRoute: () => ApiCanvasCanvasIdNodesRoute,
  } as any)
const ApiCanvasCanvasIdNodesNodeIdVersionsRoute =
  ApiCanvasCanvasIdNodesNodeIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ApiCanvasCanvasIdNodesNodeIdRoute,
  } as any)
const ApiCanvasCanvasIdNodesNodeIdGenerateRoute =
  ApiCanvasCanvasIdNodesNodeIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => ApiCanvasCanvasIdNodesNodeIdRoute,
  } as any)
const ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRoute =
  ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRouteImport.update({
    id: '/$versionId/restore',
    path: '/$versionId/restore',
    getParentRoute: () => ApiCanvasCanvasIdNodesNodeIdVersionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/health': typeof HealthRoute
  '/artifacts': typeof AppArtifactsRoute
  '/automations': typeof AppAutomationsRoute
  '/canvas': typeof AppCanvasRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/api/agent': typeof ApiAgentRoute
  '/api/artifacts': typeof ApiArtifactsRouteWithChildren
  '/api/automations': typeof ApiAutomationsRouteWithChildren
  '/api/canvas': typeof ApiCanvasRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/api/threads': typeof ApiThreadsRouteWithChildren
  '/canvas/$canvasId': typeof AppCanvasCanvasIdRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/data': typeof AppSettingsDataRoute
  '/settings/mcp': typeof AppSettingsMcpRoute
  '/settings/model': typeof AppSettingsModelRoute
  '/api/artifacts/$artifactId': typeof ApiArtifactsArtifactIdRoute
  '/api/automations/$automationId': typeof ApiAutomationsAutomationIdRouteWithChildren
  '/api/canvas/$canvasId': typeof ApiCanvasCanvasIdRouteWithChildren
  '/api/dashboard/history': typeof ApiDashboardHistoryRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/mcp/tools': typeof ApiMcpToolsRoute
  '/api/settings/mcp-token': typeof ApiSettingsMcpTokenRoute
  '/api/threads/$threadId': typeof ApiThreadsThreadIdRoute
  '/canvas/': typeof AppCanvasIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/api/automations/$automationId/runs': typeof ApiAutomationsAutomationIdRunsRoute
  '/api/canvas/$canvasId/edges': typeof ApiCanvasCanvasIdEdgesRoute
  '/api/canvas/$canvasId/nodes': typeof ApiCanvasCanvasIdNodesRouteWithChildren
  '/api/dashboard/snapshots/$snapshotId': typeof ApiDashboardSnapshotsSnapshotIdRoute
  '/api/canvas/$canvasId/nodes/$nodeId': typeof ApiCanvasCanvasIdNodesNodeIdRouteWithChildren
  '/api/canvas/$canvasId/nodes/$nodeId/generate': typeof ApiCanvasCanvasIdNodesNodeIdGenerateRoute
  '/api/canvas/$canvasId/nodes/$nodeId/versions': typeof ApiCanvasCanvasIdNodesNodeIdVersionsRouteWithChildren
  '/api/canvas/$canvasId/nodes/$nodeId/versions/$versionId/restore': typeof ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/artifacts': typeof AppArtifactsRoute
  '/automations': typeof AppAutomationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/artifacts': typeof ApiArtifactsRouteWithChildren
  '/api/automations': typeof ApiAutomationsRouteWithChildren
  '/api/canvas': typeof ApiCanvasRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/api/threads': typeof ApiThreadsRouteWithChildren
  '/': typeof AppIndexRoute
  '/canvas/$canvasId': typeof AppCanvasCanvasIdRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/data': typeof AppSettingsDataRoute
  '/settings/mcp': typeof AppSettingsMcpRoute
  '/settings/model': typeof AppSettingsModelRoute
  '/api/artifacts/$artifactId': typeof ApiArtifactsArtifactIdRoute
  '/api/automations/$automationId': typeof ApiAutomationsAutomationIdRouteWithChildren
  '/api/canvas/$canvasId': typeof ApiCanvasCanvasIdRouteWithChildren
  '/api/dashboard/history': typeof ApiDashboardHistoryRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/mcp/tools': typeof ApiMcpToolsRoute
  '/api/settings/mcp-token': typeof ApiSettingsMcpTokenRoute
  '/api/threads/$threadId': typeof ApiThreadsThreadIdRoute
  '/canvas': typeof AppCanvasIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/api/automations/$automationId/runs': typeof ApiAutomationsAutomationIdRunsRoute
  '/api/canvas/$canvasId/edges': typeof ApiCanvasCanvasIdEdgesRoute
  '/api/canvas/$canvasId/nodes': typeof ApiCanvasCanvasIdNodesRouteWithChildren
  '/api/dashboard/snapshots/$snapshotId': typeof ApiDashboardSnapshotsSnapshotIdRoute
  '/api/canvas/$canvasId/nodes/$nodeId': typeof ApiCanvasCanvasIdNodesNodeIdRouteWithChildren
  '/api/canvas/$canvasId/nodes/$nodeId/generate': typeof ApiCanvasCanvasIdNodesNodeIdGenerateRoute
  '/api/canvas/$canvasId/nodes/$nodeId/versions': typeof ApiCanvasCanvasIdNodesNodeIdVersionsRouteWithChildren
  '/api/canvas/$canvasId/nodes/$nodeId/versions/$versionId/restore': typeof ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/health': typeof HealthRoute
  '/_app/artifacts': typeof AppArtifactsRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/canvas': typeof AppCanvasRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/api/agent': typeof ApiAgentRoute
  '/api/artifacts': typeof ApiArtifactsRouteWithChildren
  '/api/automations': typeof ApiAutomationsRouteWithChildren
  '/api/canvas': typeof ApiCanvasRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/api/threads': typeof ApiThreadsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/canvas/$canvasId': typeof AppCanvasCanvasIdRoute
  '/_app/chat/$threadId': typeof AppChatThreadIdRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/data': typeof AppSettingsDataRoute
  '/_app/settings/mcp': typeof AppSettingsMcpRoute
  '/_app/settings/model': typeof AppSettingsModelRoute
  '/api/artifacts/$artifactId': typeof ApiArtifactsArtifactIdRoute
  '/api/automations/$automationId': typeof ApiAutomationsAutomationIdRouteWithChildren
  '/api/canvas/$canvasId': typeof ApiCanvasCanvasIdRouteWithChildren
  '/api/dashboard/history': typeof ApiDashboardHistoryRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/mcp/tools': typeof ApiMcpToolsRoute
  '/api/settings/mcp-token': typeof ApiSettingsMcpTokenRoute
  '/api/threads/$threadId': typeof ApiThreadsThreadIdRoute
  '/_app/canvas/': typeof AppCanvasIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/api/automations/$automationId/runs': typeof ApiAutomationsAutomationIdRunsRoute
  '/api/canvas/$canvasId/edges': typeof ApiCanvasCanvasIdEdgesRoute
  '/api/canvas/$canvasId/nodes': typeof ApiCanvasCanvasIdNodesRouteWithChildren
  '/api/dashboard/snapshots/$snapshotId': typeof ApiDashboardSnapshotsSnapshotIdRoute
  '/api/canvas/$canvasId/nodes/$nodeId': typeof ApiCanvasCanvasIdNodesNodeIdRouteWithChildren
  '/api/canvas/$canvasId/nodes/$nodeId/generate': typeof ApiCanvasCanvasIdNodesNodeIdGenerateRoute
  '/api/canvas/$canvasId/nodes/$nodeId/versions': typeof ApiCanvasCanvasIdNodesNodeIdVersionsRouteWithChildren
  '/api/canvas/$canvasId/nodes/$nodeId/versions/$versionId/restore': typeof ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/artifacts'
    | '/automations'
    | '/canvas'
    | '/dashboard'
    | '/settings'
    | '/api/agent'
    | '/api/artifacts'
    | '/api/automations'
    | '/api/canvas'
    | '/api/chat'
    | '/api/dashboard'
    | '/api/threads'
    | '/canvas/$canvasId'
    | '/chat/$threadId'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/mcp'
    | '/settings/model'
    | '/api/artifacts/$artifactId'
    | '/api/automations/$automationId'
    | '/api/canvas/$canvasId'
    | '/api/dashboard/history'
    | '/api/mcp/servers'
    | '/api/mcp/tools'
    | '/api/settings/mcp-token'
    | '/api/threads/$threadId'
    | '/canvas/'
    | '/settings/'
    | '/api/automations/$automationId/runs'
    | '/api/canvas/$canvasId/edges'
    | '/api/canvas/$canvasId/nodes'
    | '/api/dashboard/snapshots/$snapshotId'
    | '/api/canvas/$canvasId/nodes/$nodeId'
    | '/api/canvas/$canvasId/nodes/$nodeId/generate'
    | '/api/canvas/$canvasId/nodes/$nodeId/versions'
    | '/api/canvas/$canvasId/nodes/$nodeId/versions/$versionId/restore'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/artifacts'
    | '/automations'
    | '/dashboard'
    | '/api/agent'
    | '/api/artifacts'
    | '/api/automations'
    | '/api/canvas'
    | '/api/chat'
    | '/api/dashboard'
    | '/api/threads'
    | '/'
    | '/canvas/$canvasId'
    | '/chat/$threadId'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/mcp'
    | '/settings/model'
    | '/api/artifacts/$artifactId'
    | '/api/automations/$automationId'
    | '/api/canvas/$canvasId'
    | '/api/dashboard/history'
    | '/api/mcp/servers'
    | '/api/mcp/tools'
    | '/api/settings/mcp-token'
    | '/api/threads/$threadId'
    | '/canvas'
    | '/settings'
    | '/api/automations/$automationId/runs'
    | '/api/canvas/$canvasId/edges'
    | '/api/canvas/$canvasId/nodes'
    | '/api/dashboard/snapshots/$snapshotId'
    | '/api/canvas/$canvasId/nodes/$nodeId'
    | '/api/canvas/$canvasId/nodes/$nodeId/generate'
    | '/api/canvas/$canvasId/nodes/$nodeId/versions'
    | '/api/canvas/$canvasId/nodes/$nodeId/versions/$versionId/restore'
  id:
    | '__root__'
    | '/_app'
    | '/health'
    | '/_app/artifacts'
    | '/_app/automations'
    | '/_app/canvas'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/api/agent'
    | '/api/artifacts'
    | '/api/automations'
    | '/api/canvas'
    | '/api/chat'
    | '/api/dashboard'
    | '/api/threads'
    | '/_app/'
    | '/_app/canvas/$canvasId'
    | '/_app/chat/$threadId'
    | '/_app/settings/appearance'
    | '/_app/settings/data'
    | '/_app/settings/mcp'
    | '/_app/settings/model'
    | '/api/artifacts/$artifactId'
    | '/api/automations/$automationId'
    | '/api/canvas/$canvasId'
    | '/api/dashboard/history'
    | '/api/mcp/servers'
    | '/api/mcp/tools'
    | '/api/settings/mcp-token'
    | '/api/threads/$threadId'
    | '/_app/canvas/'
    | '/_app/settings/'
    | '/api/automations/$automationId/runs'
    | '/api/canvas/$canvasId/edges'
    | '/api/canvas/$canvasId/nodes'
    | '/api/dashboard/snapshots/$snapshotId'
    | '/api/canvas/$canvasId/nodes/$nodeId'
    | '/api/canvas/$canvasId/nodes/$nodeId/generate'
    | '/api/canvas/$canvasId/nodes/$nodeId/versions'
    | '/api/canvas/$canvasId/nodes/$nodeId/versions/$versionId/restore'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  HealthRoute: typeof HealthRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiArtifactsRoute: typeof ApiArtifactsRouteWithChildren
  ApiAutomationsRoute: typeof ApiAutomationsRouteWithChildren
  ApiCanvasRoute: typeof ApiCanvasRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiDashboardRoute: typeof ApiDashboardRouteWithChildren
  ApiThreadsRoute: typeof ApiThreadsRouteWithChildren
  ApiMcpServersRoute: typeof ApiMcpServersRoute
  ApiMcpToolsRoute: typeof ApiMcpToolsRoute
  ApiSettingsMcpTokenRoute: typeof ApiSettingsMcpTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/threads': {
      id: '/api/threads'
      path: '/api/threads'
      fullPath: '/api/threads'
      preLoaderRoute: typeof ApiThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas': {
      id: '/api/canvas'
      path: '/api/canvas'
      fullPath: '/api/canvas'
      preLoaderRoute: typeof ApiCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations': {
      id: '/api/automations'
      path: '/api/automations'
      fullPath: '/api/automations'
      preLoaderRoute: typeof ApiAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts': {
      id: '/api/artifacts'
      path: '/api/artifacts'
      fullPath: '/api/artifacts'
      preLoaderRoute: typeof ApiArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/canvas': {
      id: '/_app/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof AppCanvasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artifacts': {
      id: '/_app/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof AppArtifactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/canvas/': {
      id: '/_app/canvas/'
      path: '/'
      fullPath: '/canvas/'
      preLoaderRoute: typeof AppCanvasIndexRouteImport
      parentRoute: typeof AppCanvasRoute
    }
    '/api/threads/$threadId': {
      id: '/api/threads/$threadId'
      path: '/$threadId'
      fullPath: '/api/threads/$threadId'
      preLoaderRoute: typeof ApiThreadsThreadIdRouteImport
      parentRoute: typeof ApiThreadsRoute
    }
    '/api/settings/mcp-token': {
      id: '/api/settings/mcp-token'
      path: '/api/settings/mcp-token'
      fullPath: '/api/settings/mcp-token'
      preLoaderRoute: typeof ApiSettingsMcpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/tools': {
      id: '/api/mcp/tools'
      path: '/api/mcp/tools'
      fullPath: '/api/mcp/tools'
      preLoaderRoute: typeof ApiMcpToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/servers': {
      id: '/api/mcp/servers'
      path: '/api/mcp/servers'
      fullPath: '/api/mcp/servers'
      preLoaderRoute: typeof ApiMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/history': {
      id: '/api/dashboard/history'
      path: '/history'
      fullPath: '/api/dashboard/history'
      preLoaderRoute: typeof ApiDashboardHistoryRouteImport
      parentRoute: typeof ApiDashboardRoute
    }
    '/api/canvas/$canvasId': {
      id: '/api/canvas/$canvasId'
      path: '/$canvasId'
      fullPath: '/api/canvas/$canvasId'
      preLoaderRoute: typeof ApiCanvasCanvasIdRouteImport
      parentRoute: typeof ApiCanvasRoute
    }
    '/api/automations/$automationId': {
      id: '/api/automations/$automationId'
      path: '/$automationId'
      fullPath: '/api/automations/$automationId'
      preLoaderRoute: typeof ApiAutomationsAutomationIdRouteImport
      parentRoute: typeof ApiAutomationsRoute
    }
    '/api/artifacts/$artifactId': {
      id: '/api/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/api/artifacts/$artifactId'
      preLoaderRoute: typeof ApiArtifactsArtifactIdRouteImport
      parentRoute: typeof ApiArtifactsRoute
    }
    '/_app/settings/model': {
      id: '/_app/settings/model'
      path: '/model'
      fullPath: '/settings/model'
      preLoaderRoute: typeof AppSettingsModelRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/mcp': {
      id: '/_app/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof AppSettingsMcpRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/data': {
      id: '/_app/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof AppSettingsDataRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/chat/$threadId': {
      id: '/_app/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AppChatThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/canvas/$canvasId': {
      id: '/_app/canvas/$canvasId'
      path: '/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof AppCanvasCanvasIdRouteImport
      parentRoute: typeof AppCanvasRoute
    }
    '/api/dashboard/snapshots/$snapshotId': {
      id: '/api/dashboard/snapshots/$snapshotId'
      path: '/snapshots/$snapshotId'
      fullPath: '/api/dashboard/snapshots/$snapshotId'
      preLoaderRoute: typeof ApiDashboardSnapshotsSnapshotIdRouteImport
      parentRoute: typeof ApiDashboardRoute
    }
    '/api/canvas/$canvasId/nodes': {
      id: '/api/canvas/$canvasId/nodes'
      path: '/nodes'
      fullPath: '/api/canvas/$canvasId/nodes'
      preLoaderRoute: typeof ApiCanvasCanvasIdNodesRouteImport
      parentRoute: typeof ApiCanvasCanvasIdRoute
    }
    '/api/canvas/$canvasId/edges': {
      id: '/api/canvas/$canvasId/edges'
      path: '/edges'
      fullPath: '/api/canvas/$canvasId/edges'
      preLoaderRoute: typeof ApiCanvasCanvasIdEdgesRouteImport
      parentRoute: typeof ApiCanvasCanvasIdRoute
    }
    '/api/automations/$automationId/runs': {
      id: '/api/automations/$automationId/runs'
      path: '/runs'
      fullPath: '/api/automations/$automationId/runs'
      preLoaderRoute: typeof ApiAutomationsAutomationIdRunsRouteImport
      parentRoute: typeof ApiAutomationsAutomationIdRoute
    }
    '/api/canvas/$canvasId/nodes/$nodeId': {
      id: '/api/canvas/$canvasId/nodes/$nodeId'
      path: '/$nodeId'
      fullPath: '/api/canvas/$canvasId/nodes/$nodeId'
      preLoaderRoute: typeof ApiCanvasCanvasIdNodesNodeIdRouteImport
      parentRoute: typeof ApiCanvasCanvasIdNodesRoute
    }
    '/api/canvas/$canvasId/nodes/$nodeId/versions': {
      id: '/api/canvas/$canvasId/nodes/$nodeId/versions'
      path: '/versions'
      fullPath: '/api/canvas/$canvasId/nodes/$nodeId/versions'
      preLoaderRoute: typeof ApiCanvasCanvasIdNodesNodeIdVersionsRouteImport
      parentRoute: typeof ApiCanvasCanvasIdNodesNodeIdRoute
    }
    '/api/canvas/$canvasId/nodes/$nodeId/generate': {
      id: '/api/canvas/$canvasId/nodes/$nodeId/generate'
      path: '/generate'
      fullPath: '/api/canvas/$canvasId/nodes/$nodeId/generate'
      preLoaderRoute: typeof ApiCanvasCanvasIdNodesNodeIdGenerateRouteImport
      parentRoute: typeof ApiCanvasCanvasIdNodesNodeIdRoute
    }
    '/api/canvas/$canvasId/nodes/$nodeId/versions/$versionId/restore': {
      id: '/api/canvas/$canvasId/nodes/$nodeId/versions/$versionId/restore'
      path: '/$versionId/restore'
      fullPath: '/api/canvas/$canvasId/nodes/$nodeId/versions/$versionId/restore'
      preLoaderRoute: typeof ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRouteImport
      parentRoute: typeof ApiCanvasCanvasIdNodesNodeIdVersionsRoute
    }
  }
}

interface AppCanvasRouteChildren {
  AppCanvasCanvasIdRoute: typeof AppCanvasCanvasIdRoute
  AppCanvasIndexRoute: typeof AppCanvasIndexRoute
}

const AppCanvasRouteChildren: AppCanvasRouteChildren = {
  AppCanvasCanvasIdRoute: AppCanvasCanvasIdRoute,
  AppCanvasIndexRoute: AppCanvasIndexRoute,
}

const AppCanvasRouteWithChildren = AppCanvasRoute._addFileChildren(
  AppCanvasRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsDataRoute: typeof AppSettingsDataRoute
  AppSettingsMcpRoute: typeof AppSettingsMcpRoute
  AppSettingsModelRoute: typeof AppSettingsModelRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsDataRoute: AppSettingsDataRoute,
  AppSettingsMcpRoute: AppSettingsMcpRoute,
  AppSettingsModelRoute: AppSettingsModelRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppArtifactsRoute: typeof AppArtifactsRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppCanvasRoute: typeof AppCanvasRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppChatThreadIdRoute: typeof AppChatThreadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArtifactsRoute: AppArtifactsRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppCanvasRoute: AppCanvasRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppChatThreadIdRoute: AppChatThreadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiArtifactsRouteChildren {
  ApiArtifactsArtifactIdRoute: typeof ApiArtifactsArtifactIdRoute
}

const ApiArtifactsRouteChildren: ApiArtifactsRouteChildren = {
  ApiArtifactsArtifactIdRoute: ApiArtifactsArtifactIdRoute,
}

const ApiArtifactsRouteWithChildren = ApiArtifactsRoute._addFileChildren(
  ApiArtifactsRouteChildren,
)

interface ApiAutomationsAutomationIdRouteChildren {
  ApiAutomationsAutomationIdRunsRoute: typeof ApiAutomationsAutomationIdRunsRoute
}

const ApiAutomationsAutomationIdRouteChildren: ApiAutomationsAutomationIdRouteChildren =
  {
    ApiAutomationsAutomationIdRunsRoute: ApiAutomationsAutomationIdRunsRoute,
  }

const ApiAutomationsAutomationIdRouteWithChildren =
  ApiAutomationsAutomationIdRoute._addFileChildren(
    ApiAutomationsAutomationIdRouteChildren,
  )

interface ApiAutomationsRouteChildren {
  ApiAutomationsAutomationIdRoute: typeof ApiAutomationsAutomationIdRouteWithChildren
}

const ApiAutomationsRouteChildren: ApiAutomationsRouteChildren = {
  ApiAutomationsAutomationIdRoute: ApiAutomationsAutomationIdRouteWithChildren,
}

const ApiAutomationsRouteWithChildren = ApiAutomationsRoute._addFileChildren(
  ApiAutomationsRouteChildren,
)

interface ApiCanvasCanvasIdNodesNodeIdVersionsRouteChildren {
  ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRoute: typeof ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRoute
}

const ApiCanvasCanvasIdNodesNodeIdVersionsRouteChildren: ApiCanvasCanvasIdNodesNodeIdVersionsRouteChildren =
  {
    ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRoute:
      ApiCanvasCanvasIdNodesNodeIdVersionsVersionIdRestoreRoute,
  }

const ApiCanvasCanvasIdNodesNodeIdVersionsRouteWithChildren =
  ApiCanvasCanvasIdNodesNodeIdVersionsRoute._addFileChildren(
    ApiCanvasCanvasIdNodesNodeIdVersionsRouteChildren,
  )

interface ApiCanvasCanvasIdNodesNodeIdRouteChildren {
  ApiCanvasCanvasIdNodesNodeIdGenerateRoute: typeof ApiCanvasCanvasIdNodesNodeIdGenerateRoute
  ApiCanvasCanvasIdNodesNodeIdVersionsRoute: typeof ApiCanvasCanvasIdNodesNodeIdVersionsRouteWithChildren
}

const ApiCanvasCanvasIdNodesNodeIdRouteChildren: ApiCanvasCanvasIdNodesNodeIdRouteChildren =
  {
    ApiCanvasCanvasIdNodesNodeIdGenerateRoute:
      ApiCanvasCanvasIdNodesNodeIdGenerateRoute,
    ApiCanvasCanvasIdNodesNodeIdVersionsRoute:
      ApiCanvasCanvasIdNodesNodeIdVersionsRouteWithChildren,
  }

const ApiCanvasCanvasIdNodesNodeIdRouteWithChildren =
  ApiCanvasCanvasIdNodesNodeIdRoute._addFileChildren(
    ApiCanvasCanvasIdNodesNodeIdRouteChildren,
  )

interface ApiCanvasCanvasIdNodesRouteChildren {
  ApiCanvasCanvasIdNodesNodeIdRoute: typeof ApiCanvasCanvasIdNodesNodeIdRouteWithChildren
}

const ApiCanvasCanvasIdNodesRouteChildren: ApiCanvasCanvasIdNodesRouteChildren =
  {
    ApiCanvasCanvasIdNodesNodeIdRoute:
      ApiCanvasCanvasIdNodesNodeIdRouteWithChildren,
  }

const ApiCanvasCanvasIdNodesRouteWithChildren =
  ApiCanvasCanvasIdNodesRoute._addFileChildren(
    ApiCanvasCanvasIdNodesRouteChildren,
  )

interface ApiCanvasCanvasIdRouteChildren {
  ApiCanvasCanvasIdEdgesRoute: typeof ApiCanvasCanvasIdEdgesRoute
  ApiCanvasCanvasIdNodesRoute: typeof ApiCanvasCanvasIdNodesRouteWithChildren
}

const ApiCanvasCanvasIdRouteChildren: ApiCanvasCanvasIdRouteChildren = {
  ApiCanvasCanvasIdEdgesRoute: ApiCanvasCanvasIdEdgesRoute,
  ApiCanvasCanvasIdNodesRoute: ApiCanvasCanvasIdNodesRouteWithChildren,
}

const ApiCanvasCanvasIdRouteWithChildren =
  ApiCanvasCanvasIdRoute._addFileChildren(ApiCanvasCanvasIdRouteChildren)

interface ApiCanvasRouteChildren {
  ApiCanvasCanvasIdRoute: typeof ApiCanvasCanvasIdRouteWithChildren
}

const ApiCanvasRouteChildren: ApiCanvasRouteChildren = {
  ApiCanvasCanvasIdRoute: ApiCanvasCanvasIdRouteWithChildren,
}

const ApiCanvasRouteWithChildren = ApiCanvasRoute._addFileChildren(
  ApiCanvasRouteChildren,
)

interface ApiDashboardRouteChildren {
  ApiDashboardHistoryRoute: typeof ApiDashboardHistoryRoute
  ApiDashboardSnapshotsSnapshotIdRoute: typeof ApiDashboardSnapshotsSnapshotIdRoute
}

const ApiDashboardRouteChildren: ApiDashboardRouteChildren = {
  ApiDashboardHistoryRoute: ApiDashboardHistoryRoute,
  ApiDashboardSnapshotsSnapshotIdRoute: ApiDashboardSnapshotsSnapshotIdRoute,
}

const ApiDashboardRouteWithChildren = ApiDashboardRoute._addFileChildren(
  ApiDashboardRouteChildren,
)

interface ApiThreadsRouteChildren {
  ApiThreadsThreadIdRoute: typeof ApiThreadsThreadIdRoute
}

const ApiThreadsRouteChildren: ApiThreadsRouteChildren = {
  ApiThreadsThreadIdRoute: ApiThreadsThreadIdRoute,
}

const ApiThreadsRouteWithChildren = ApiThreadsRoute._addFileChildren(
  ApiThreadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  HealthRoute: HealthRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiArtifactsRoute: ApiArtifactsRouteWithChildren,
  ApiAutomationsRoute: ApiAutomationsRouteWithChildren,
  ApiCanvasRoute: ApiCanvasRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiDashboardRoute: ApiDashboardRouteWithChildren,
  ApiThreadsRoute: ApiThreadsRouteWithChildren,
  ApiMcpServersRoute: ApiMcpServersRoute,
  ApiMcpToolsRoute: ApiMcpToolsRoute,
  ApiSettingsMcpTokenRoute: ApiSettingsMcpTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
