/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsModelRouteImport } from './routes/settings/model'
import { Route as SettingsMcpRouteImport } from './routes/settings/mcp'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiThreadsRouteImport } from './routes/api/threads'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiThreadsThreadIdRouteImport } from './routes/api/threads.$threadId'
import { Route as ApiMcpToolsRouteImport } from './routes/api/mcp/tools'
import { Route as ApiMcpServersRouteImport } from './routes/api/mcp/servers'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelRoute = SettingsModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadsRoute = ApiThreadsRouteImport.update({
  id: '/api/threads',
  path: '/api/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadsThreadIdRoute = ApiThreadsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ApiThreadsRoute,
} as any)
const ApiMcpToolsRoute = ApiMcpToolsRouteImport.update({
  id: '/api/mcp/tools',
  path: '/api/mcp/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpServersRoute = ApiMcpServersRouteImport.update({
  id: '/api/mcp/servers',
  path: '/api/mcp/servers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/threads': typeof ApiThreadsRouteWithChildren
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/mcp/tools': typeof ApiMcpToolsRoute
  '/api/threads/$threadId': typeof ApiThreadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/threads': typeof ApiThreadsRouteWithChildren
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings': typeof SettingsIndexRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/mcp/tools': typeof ApiMcpToolsRoute
  '/api/threads/$threadId': typeof ApiThreadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/threads': typeof ApiThreadsRouteWithChildren
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/mcp/tools': typeof ApiMcpToolsRoute
  '/api/threads/$threadId': typeof ApiThreadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/settings'
    | '/api/chat'
    | '/api/threads'
    | '/chat/$threadId'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/mcp'
    | '/settings/model'
    | '/settings/'
    | '/api/mcp/servers'
    | '/api/mcp/tools'
    | '/api/threads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/api/chat'
    | '/api/threads'
    | '/chat/$threadId'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/mcp'
    | '/settings/model'
    | '/settings'
    | '/api/mcp/servers'
    | '/api/mcp/tools'
    | '/api/threads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/settings'
    | '/api/chat'
    | '/api/threads'
    | '/chat/$threadId'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/mcp'
    | '/settings/model'
    | '/settings/'
    | '/api/mcp/servers'
    | '/api/mcp/tools'
    | '/api/threads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiThreadsRoute: typeof ApiThreadsRouteWithChildren
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ApiMcpServersRoute: typeof ApiMcpServersRoute
  ApiMcpToolsRoute: typeof ApiMcpToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/model': {
      id: '/settings/model'
      path: '/model'
      fullPath: '/settings/model'
      preLoaderRoute: typeof SettingsModelRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threads': {
      id: '/api/threads'
      path: '/api/threads'
      fullPath: '/api/threads'
      preLoaderRoute: typeof ApiThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threads/$threadId': {
      id: '/api/threads/$threadId'
      path: '/$threadId'
      fullPath: '/api/threads/$threadId'
      preLoaderRoute: typeof ApiThreadsThreadIdRouteImport
      parentRoute: typeof ApiThreadsRoute
    }
    '/api/mcp/tools': {
      id: '/api/mcp/tools'
      path: '/api/mcp/tools'
      fullPath: '/api/mcp/tools'
      preLoaderRoute: typeof ApiMcpToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/servers': {
      id: '/api/mcp/servers'
      path: '/api/mcp/servers'
      fullPath: '/api/mcp/servers'
      preLoaderRoute: typeof ApiMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsModelRoute: typeof SettingsModelRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsModelRoute: SettingsModelRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiThreadsRouteChildren {
  ApiThreadsThreadIdRoute: typeof ApiThreadsThreadIdRoute
}

const ApiThreadsRouteChildren: ApiThreadsRouteChildren = {
  ApiThreadsThreadIdRoute: ApiThreadsThreadIdRoute,
}

const ApiThreadsRouteWithChildren = ApiThreadsRoute._addFileChildren(
  ApiThreadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiThreadsRoute: ApiThreadsRouteWithChildren,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ApiMcpServersRoute: ApiMcpServersRoute,
  ApiMcpToolsRoute: ApiMcpToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
