name: Quarterly - Install NPM Packages from Azure Artifacts (Windows) Push Nuget Package to Azure Artifacts and Octopus Deploy

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build-and-package:
    name: Build NPM Package and Create NuGet Package
    uses: PaycorInc/Paycor-Reusable-Actions/.github/workflows/npm-build-package-publish-reusable.yml@main
    with:
      build-command: ${{ vars.BUILD_COMMAND }}
      node-version: ${{ vars.NODE_VERSION }}
      nuspec-file: ${{ vars.NUSPEC_FILE }}
      nuget-package-name: ${{ vars.NUGET_PACKAGE_NAME }}
      azure-artifacts-feed-url: ${{ vars.AZURE_ARTIFACTS_NUGET_URL }}
      base-version: ${{ vars.BASE_VERSION_QUARTERLY }}
    secrets:
      azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

  deploy-to-octopus:
    name: Deploy to Octopus
    needs: build-and-package
    uses: PaycorInc/Paycor-Reusable-Actions/.github/workflows/octopus-release.yml@main
    with:
      octopus-release-number: ${{ needs.build-and-package.outputs.octopus-release-number }}
      octopus-operation-type: ${{ vars.OCTOPUS_CREATEANDDEPLOY_OPERATION }}
      octopus-project-name: ${{ vars.OCTOPUS_PROJECT_NAME }} #repo var 
      octopus-package-name: ${{ vars.OCTOPUS_PACKAGE_NAME }} #repo var 
      deploy-step-name: ${{ vars.DEPLOY_STEP_NAME }} #repo var 
      octopus-environment-name: ${{ vars.OCTOPUS_ENVIRONMENTS_QUARTERLY }}
      github-commit-sha: ${{ github.sha }}
      github-branch-name: ${{ github.ref_name }}
      github-build-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      apim-url: ${{ vars.APIM_PROD_URL }}
      octopus-sleep-seconds: ${{ vars.OCTOPUS_RETRY_SLEEP_SECONDS }}
      octopus-retry-max: ${{ vars.OCTOPUS_RETRY_MAX }}
    secrets:
      devopstoolbag-apim-key: ${{ secrets.DEVOPSTOOLBAG_APIM_PRODUCTION }}